A=float(input("Enter the value of the First Number :"))
B=float(input("Enter the value of the Second Number :"))
C=A+B
D=A-B
E=A*B
F=A/B
print("Sum =", C)
print("Difference =", D)
print("Product =", E)
print("Quotient =", F)
